name: Build and Deploy

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build the project (replace with your build command if needed)
      - name: Build
        run: dotnet build --configuration Release
      
      # Increment version in .nuspec file
      - name: Increment Version
        id: version
        run: |
          PACKAGE_VERSION=$(dotnet list package YourPackageName --format=short | awk '{print $2}')
          PACKAGE_VERSION=${PACKAGE_VERSION//[[:space:]]/}
          echo "Package version: $PACKAGE_VERSION"
          NEW_VERSION=$(dotnet nuspec update DapperAutoData.nuspec --version-suffix $PACKAGE_VERSION)
          echo "New version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"


      
      # Pack the project
      - name: Pack
        run: dotnet pack --configuration Release --output ./packages
      
      # Publish the package to NuGet
      - name: Publish to NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Upload Package
        run: dotnet nuget push ./packages/*.nupkg --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key "${{ secrets.NUGET_API_KEY }}"
