name: Build and Deploy

on:
  push:
    branches:
      - master
    workflow_dispatch: # This enables the manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build --configuration Release

      - name: Extract version
        id: get_version
        run: |
          version=$(grep '<Version>' ./DapperAutoData/DapperAutoData.csproj | sed 's|<Version>\(.*\)</Version>|\1|g' | tr -d '[:space:]')
          echo "VERSION=$version"
          echo "::set-output name=version::$version"
        shell: bash
      
      - name: Pack
        run: dotnet pack DapperAutoData/DapperAutoData.csproj --configuration Release
      
      - name: List directories
        run: ls -Rla ./DapperAutoData/bin/Release
      
      - name: Publish to NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      
      - name: Upload Package
        run: dotnet nuget push ./DapperAutoData/bin/Release/DapperAutoData.${{ steps.get_version.outputs.version }}.nupkg --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key "${{ secrets.NUGET_API_KEY }}"
