name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build the project (replace with your build command if needed)
      - name: Build
        run: dotnet build --configuration Release

      # Output the packages 
      - name: Output Packages
        run: dotnet list package --format json
      
      # Increment version in .nuspec file
